### ISSUE TITLE
表格分页搜索和删除BUG！！！

### ISSUE THREAD

**Issue by SourceLin** [elunez/eladmin-qd#20]
问题一
第二页时点搜索，表格数据刷新到第一页，但当前页码数不变！
问题二
删除第二页最后一条数据时，第一页的最后一条数据不显示；

问题一：
image
![image](https://user-images.githubusercontent.com/40617196/59990224-e2fb3f00-9674-11e9-9850-b9cf9f82fabb.png)

问题二：
image
![image](https://user-images.githubusercontent.com/40617196/59990231-e8588980-9674-11e9-99ad-ada2b29276f4.png)

image
![image](https://user-images.githubusercontent.com/40617196/59990232-ebec1080-9674-11e9-9185-43392e2e7489.png)

Link to minimal reproduction（最小可在线还原demo）
字典管理模块11条数据进行测试

**Comment by elunez** [comment]
已完成修复
