### ISSUE TITLE
打包好慢，要20多分钟，生成200多个js css 不知是不是这个原因，求解决思路，谢谢了

### ISSUE THREAD

**Issue by curryhh** [elunez/eladmin-qd#22]

**Comment by elunez** [comment]
2.1 版本优化了打包速度，你可以对照着修改
![image](https://user-images.githubusercontent.com/42142420/61859244-543f4380-aefa-11e9-97f7-b69790e94f85.png)与package.json

**Comment by curryhh** [comment]
好的我试试
