### ISSUE TITLE
打包会把所有页面都打包，包括后台返回的system，想问下逻辑在哪里，router.js都没引入system目录下的页面

### ISSUE THREAD

**Issue by curryhh** [elunez/eladmin-qd#24]

**Comment by elunez** [comment]
router/index.js

**Comment by curryhh** [comment]
> router/index.js

哪里只有基础的constantRouterMap，没有动态addrouter的路由，为什么会打包所有的呢？有点搞不懂求大佬解释

**Comment by elunez** [comment]
打包和路由没多大关系吧，路由是后台返回的

**Comment by curryhh** [comment]
> 打包和路由没多大关系吧，路由是后台返回的

我知道是后台返回，webpack不是递归import进来的包 插件进行打包吗？不懂的就是比如system下的好多页面的都有没在router文件里面import，而是后台返回之后用的，搞不懂，求解释下，谢谢了

**Comment by elunez** [comment]
这方面我也没怎么研究，应该是用到了路由懒加载

**Comment by curryhh** [comment]
> 这方面我也没怎么研究，应该是用到了路由懒加载

我找了好久都没找到是哪里弄的？想升级vue3.0但是你这个还没搞懂不敢弄

**Comment by wensonsmith** [comment]
我也是卡在这里了， 讲道理 webpack 打包要有 import 他才会进行打包， views 下面的我找遍了代码也没找到从哪里进行 import 的。比如 `views/monitor/log/index.vue` 没找到任何地方 `import` 了，但是打包的时候就打包进去了。。。

就是 vue-element-admin 里面也是用一个路由表进行 import， 不管懒加载还是直接加载，只要有 import 就能正常打包。 

但是这个项目里不知道怎么搞的。。 views 下面是用了什么黑魔法 , 为啥就能直接打包了，只有这里进行打包了，后面 `permission.js` 里面的 `loadViews` 才有作用啊.

@curryhh @elunez   找到原因了么？

**Comment by wensonsmith** [comment]
还是被我找到原因了呀！

原因是 [Webpack 打包机制](https://github.com/PanJiaChen/vue-element-admin/issues/292#issuecomment-346361645) ，如果代码中如果出现 `import ('@views' + 变量)`，那么 `webpack` 会默认把 `@views` 下面所有文件进行打包。。。

造成这个原因的就是 `store/modules/permission.js` 的 `loadView` 函数

```
export const loadView = (view) => { // 路由懒加载
  return () => import(`@/views/${view}`)
}
``` 

如果把这注释掉，就不会打包 `@views` 下面所有 `vue` 文件了。

**Comment by curryhh** [comment]
> 还是被我找到原因了呀！
> 
> 原因是 [Webpack 打包机制](https://github.com/PanJiaChen/vue-element-admin/issues/292#issuecomment-346361645) ，如果代码中如果出现 `import ('@views' + 变量)`，那么 `webpack` 会默认把 `@views` 下面所有文件进行打包。。。
> 
> 造成这个原因的就是 `store/modules/permission.js` 的 `loadView` 函数
> 
> ```
> export const loadView = (view) => { // 路由懒加载
>   return () => import(`@/views/${view}`)
> }
> ```
> 
> 如果把这注释掉，就不会打包 `@views` 下面所有 `vue` 文件了。

明白了 谢谢大佬
