### ISSUE TITLE
build:prod应该使用相对路径

### ISSUE THREAD

**Issue by fusionshen** [elunez/eladmin-qd#25]
[位置](https://github.com/elunez/eladmin-qd/blob/master/config/index.js#L60)
应改为:
` assetsPublicPath: './',`

**Comment by elunez** [comment]
assetsPublicPath: '/' 这个会有什么问题吗

**Comment by fusionshen** [comment]
因为打包后的文件不一定放在网络服务器根目录

**Comment by fusionshen** [comment]
因为打包后的文件不一定放在网络服务器根目录
