### ISSUE TITLE
前端页面新增小bug

### ISSUE THREAD

**Issue by xuanke90** [elunez/eladmin-qd#26]
<img width="632" alt="2019-08-29_162848" src="https://user-images.githubusercontent.com/31641185/63924145-56a53800-ca7a-11e9-9a32-7255a00e2973.png">
点击编辑按钮弹出模态框后，直接点击小叉（不是点击取消按钮），再点击新增按钮新增数据，则会回显上一次点击的数据，如果更改则不会新增数据，则会更改数据

**Comment by elunez** [comment]
看 element 文档，加一个 close 事件就好了
