### ISSUE TITLE
ie浏览器无法访问

### ISSUE THREAD

**Issue by huangxunlei** [elunez/eladmin-qd#28]
我ie11版本的浏览器无法访问,页面都加载不出来

**Comment by elunez** [comment]
simple-drawing-board 版本太高了，你改成1.4.1，就可以了

**Comment by huangxunlei** [comment]
好的，谢谢，改了就可以了。




------------------ 原始邮件 ------------------
发件人: "elunez"<notifications@github.com>;
发送时间: 2019年9月8日(星期天) 上午10:43
收件人: "elunez/eladmin-qd"<eladmin-qd@noreply.github.com>;
抄送: "2240932126"<2240932126@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [elunez/eladmin-qd] ie浏览器无法访问 (#28)




simple-drawing-board 版本太高了，你改成1.4.1，就可以了
