### ISSUE TITLE
yarn 报错

### ISSUE THREAD

**Issue by hqzh** [elunez/eladmin-qd#35]
![image](https://user-images.githubusercontent.com/26128706/65128103-62f23480-da2b-11e9-924c-350837cdd2f3.png)
win 10 ,node 10.15.3

**Comment by hqzh** [comment]
node 8.14.1正常  ，packpage那里说明一下吧

**Comment by elunez** [comment]
用 npm 配置阿里镜像仓库，不会出错，yarn 没用过
