### ISSUE TITLE
if there's nested data, rowKey is required.

### ISSUE THREAD

**Issue by qee-wong** [elunez/eladmin-qd#7]
element-ui版本降到2.4.6可以，element-ui版本2.7貌似也不行

**Comment by jwf1173** [comment]
> element-ui版本降到2.4.6可以，element-ui版本2.7貌似也不行
我也出现了这个问题，有没有解决方法呢

**Comment by elunez** [comment]
![image](https://user-images.githubusercontent.com/42142420/55713546-7a140b80-5a23-11e9-9847-ebae4c0c9861.png)
改成2.4.6

**Comment by liangjinghao6** [comment]
sb

**Comment by isLing666** [comment]
同样都是谷歌，element2.6.1的，为什么有些打开会这样，有些不会？
